<?php
/**
 * Plugin Name: Taleemi Wazaif Checker
 * Description: A modern, card-style tool to check eligibility for Taleemi Wazaif. Use shortcode [taleemi_wazaif_checker] to display.
 * Version: 1.0
 * Author: Antigravity
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly.
}

// Enqueue scripts and styles
function taleemi_wazaif_enqueue_scripts() {
    $css_version = file_exists(plugin_dir_path(__FILE__) . 'style.css') ? filemtime(plugin_dir_path(__FILE__) . 'style.css') : '1.1';
    $js_version = file_exists(plugin_dir_path(__FILE__) . 'script.js') ? filemtime(plugin_dir_path(__FILE__) . 'script.js') : '1.1';
    
    wp_enqueue_style('taleemi-wazaif-style', plugin_dir_url(__FILE__) . 'style.css', array(), $css_version);
    wp_enqueue_script('taleemi-wazaif-script', plugin_dir_url(__FILE__) . 'script.js', array(), $js_version, true);
}
add_action('wp_enqueue_scripts', 'taleemi_wazaif_enqueue_scripts');

// Shortcode
function taleemi_wazaif_shortcode() {
    ob_start();
    ?>
    <div class="app-container" id="taleemi-wrapper" dir="ltr">
        <div class="card">
            <div class="header">
                <h2><span class="icon">🎓</span> <span id="app-title">Taleemi Wazaif Checker</span></h2>
            </div>
            
            <div class="language-toggle">
                <button id="lang-btn" class="lang-btn" onclick="toggleLanguage()" type="button">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="globe-icon" style="color: #0284c7;">
                        <circle cx="12" cy="12" r="10"></circle>
                        <line x1="2" y1="12" x2="22" y2="12"></line>
                        <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path>
                    </svg>
                    <span id="lang-text">اردو / English</span>
                </button>
            </div>

            <div class="form-container">
                <div class="form-group">
                    <input type="number" id="age" min="1" max="50" placeholder="Enter your age (e.g. 19)" class="input-field" aria-label="Age">
                </div>

                <div class="form-group">
                    <select id="class-level" class="input-field select-field" aria-label="Class Level">
                        <!-- Options generated by JS -->
                    </select>
                </div>

                <button id="check-btn" class="primary-btn" onclick="handleCheck()" type="button">
                    Check Eligibility
                </button>
                
                <button id="reset-btn" class="secondary-btn" onclick="handleReset()" type="button">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" class="reset-icon">
                        <path d="M21.5 2v6h-6M21.34 15.57a10 10 0 1 1-.34-9.37l5.63 5.4" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg> 
                    <span id="reset-text">Reset</span>
                </button>

                <div id="result-container" class="result-container hidden">
                    <div id="result-icon"></div>
                    <span id="result-msg"></span>
                </div>
            </div>
        </div>
    </div>
    <?php
    return ob_get_clean();
}
add_shortcode('taleemi_wazaif_checker', 'taleemi_wazaif_shortcode');
